### ISSUE TITLE
Integrate with SwiftyStoreKit

### ISSUE THREAD

**Issue by MaxHasADHD** [MosheBerman/PatronKit#4]
Instead of handling all of the store kit part, it might be beneficial to use SwiftyStoreKit and then this library can focus on saving users to the cloud and displaying that data maybe?

https://github.com/bizz84/SwiftyStoreKit

**Comment by MosheBerman** [comment]
That's not a bad idea, but what's the benefit of adding a dependency now that the StoreKit implementation is already done? Does this somehow conflict with apps using SwiftyStoreKit?

**Comment by MaxHasADHD** [comment]
It does not (as far as I know). Just a quick thought I had. Could be good just in case anything changes (Probably unlikely, or drastically, but..) and then this library would just focus on displaying a patron view and saving to the cloud and doesn't need to manage any of the purchasing. Cons would be if SwiftyStoreKit got a bug, then so would PatronKit.

**Comment by MosheBerman** [comment]
I think we're going to stick with the vanilla implementation for now. Thanks for the suggestion!

**Comment by MosheBerman** [comment]
I'm rethinking this a little bit. I had a similar thought earlier today.
